### PR TITLE
Fixes #16

### LINKED ISSUE #16: Semicolon or newline shouldn't be required before EOF
At the moment you need to have a semicolon or newline before the EOF of a program/script:

This works:

```
print("Hello!");[EOF]
```

This works:

```
print("Hello!")
[EOF]
```

But this doesn't work:

```
print("Hello!")[EOF]
```

Unfortunately the changes in https://github.com/liam4/tlnccuwagnf/commit/15eff2a948125a245100639e4c0bdd26f3d17387 caused an ambiguity problem when a script ended with a newline just before the EOF.

### PR DESCRIPTION
**Pull request by bates64**
#16

### CODE REVIEW

File: src/run.js [hunk 1]
```diff
@@ -3,6 +3,7 @@ var grammar = require('./grammar');
 var interp = require('./interp');
 
 export function run(code, options) {
+  code = code += '\n'
```
Comment (towerofnix) [inline src/run.js]: Uh.. Shouldn't this be

```
code += '\n'
```

or

```
code = code + '\n'
```

?

Also you're missing a semicolon there (oh the irony).

**Comment by towerofnix** [comment]
Will :shipit: after you fix that :P

**Comment by bates64** [comment]
oops 📦
